### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by maurobender** [matt-d-rat/react-middle-truncate#3]
## Report

**Describe the bug**
When I include the module in the project a *Failed to compile* error starts showing.

**Steps to Reproduce**
Just include the library in the project and try to use it.

**Expected behaviour**
Be able to use the library and run the project as expected.

**Screenshots**
![Failed to compile](https://i.imgur.com/kllkrMX.png)

## Other Information

**React**
- `react`: 16.4.0
- `react-dom`:  16.4.0

**Desktop**
 - OS: macOS 10.14.4 (18E226)
 - Browser: chrome
 - Version: 73.0.3683.86 (Build oficial) (64 bits)

**Comment by brightsider** [comment]
Same problem. Any solution?

**Comment by episodeyang** [comment]
Any updates on this issue?

**Comment by episodeyang** [comment]
I am having the same issue

```bash
./node_modules/react-middle-truncate/src/react-middle-truncate/middle-truncate.jsx 21:19
Module parse failed: Unexpected token (21:19)
You may need an appropriate loader to handle this file type.
| // a Regular Expression to calculate these positions dynamically against the text itself.
| class MiddleTruncate extends PureComponent {
>   static propTypes = {
|     className: PropTypes.string,
|     ellipsis: PropTypes.string,
```

**Comment by justin-cotarla** [comment]
Importing the module via `import MiddleTruncate from "react-middle-truncate"` brings in the untranspiled module. Either:
1. Add an exception to your babel-loader's exclude: `exclude: /node_modules(?!\/react-middle-truncate)/`
2. Import the transpiled module: `import MiddleTruncate from "react-middle-truncate/lib/react-middle-truncate"`

**Comment by matt-d-rat** [comment]
This package declares two entry points in its `package.json`:

- `"main": "lib/react-middle-truncate.js"` (ES5 module)
- `"module": "src/react-middle-truncate/index.js"` (ES6 module)

If you are using a module bundler such as [Webpack](https://webpack.js.org/), then it is most likely that your module bundler is prioritising the `module` import over `main` – this is the default behaviour for `webpack` (see [`mainFields`](https://webpack.js.org/configuration/resolve/#resolvemainfields) docs).

You can change this prioritisation, but doing so may cause other npm modules to break.

As pointed out by @justin-cotarla, you're left with two options:

> 1. Add an exception to your babel-loader's exclude:
`exclude /node_modules(?!\/react-middle-truncate)/`
> 2. or, import the transpiled module instead:
`import MiddleTruncate from "react-middle-truncate/lib/react-middle-truncate"`
